INHERIT: utils/mkdocs-base.yml

site_name: 香山开源处理器用户手册
repo_url: https://github.com/OpenXiangShan/XiangShan-User-Guide
repo_name: XiangShan-User-Guide

nav:
  - 前言: index.md
  - 概述: introduction.md
  - 微架构简介: processor.md
  - 指令集: instruction-set.md
  - 数据寄存器: registers.md
  - 特权模式与控制状态寄存器: mode-and-csr.md
  - 异常与中断: exception-and-interrupt.md
  - 内存模型: memory-model.md
  - 内存子系统: memory-subsystem.md
  - 向量: vector.md
  - 中断控制器: interruption-controller.md
  - 总线接口: bus-interface.md
  - 调试: debug.md
  - 性能监测单元: performance-monitor.md
