site_name: 香山开源处理器用户手册
theme:
  name: material
  features:
    - navigation.indexes

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - abbr
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - def_list
  - markdown_grid_tables
  - markdown_captions     # for image caption, use alt as caption
  - table_captions:       # for table caption, use Table: xxxx
      numbering: false
  - remove_references
  - remove_include
  - replace_variables:
      variables:
        processor_name: "昆明湖 V2R2"

plugins:


nav:
  - 前言: index.md
  - 概述: introduction.md
  - 微架构简介: processor.md
  - 指令集: instruction-set.md
  - 数据寄存器: registers.md
  - 特权模式与控制状态寄存器: mode-and-csr.md
  - 异常与中断: exception-and-interrupt.md
  - 内存模型: memory-model.md
  - 内存子系统: memory-subsystem.md
  - 向量: vector.md
  - 中断控制器: interruption-controller.md
  - 总线接口: bus-interface.md
  - 调试: debug.md
  - 性能监测单元: performance-monitor.md
