name: build document with pandoc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/openxiangshan/docs-utils:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-tags: true

      - name: build
        env:
          HOME: /root
        run: |
          git config --global --add safe.directory $(pwd)
          make

      - name: Upload built pdf
        uses: actions/upload-artifact@v4
        with:
          name: xiangshan-user-guide-pdf
          path: xiangshan-user-guide.pdf

      - name: Upload built html
        uses: actions/upload-artifact@v4
        with:
          name: xiangshan-user-guide-html
          path: xiangshan-user-guide.html
