name: build document with pandoc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/openxiangshan/docs-utils:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        lang: [zh, en]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-tags: true

      - name: Build PDFs
        env:
          HOME: /root
        run: |
          git config --global --add safe.directory $(pwd)
          make pdf-one LANG=${{ matrix.lang }}
          make pdf-one LANG=${{ matrix.lang }} TWOSIDE=1

      - name: Upload built PDFs
        uses: actions/upload-artifact@v4
        with:
          name: xiangshan-user-guide-${{ matrix.lang }}
          path: |
            xiangshan-user-guide-${{ matrix.lang }}.pdf
            xiangshan-user-guide-twoside-${{ matrix.lang }}.pdf
