name: build document with pandoc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment variables
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Install dependency
        run: |
          ./resources/dependency.sh

      - name: build
        run: |
          make
      
      - name: Upload built pdf
        uses: actions/upload-artifact@v4
        with:
          name: xiangshan-user-guide-pdf
          path: xiangshan-user-guide.pdf
      
      - name: Upload built html
        uses: actions/upload-artifact@v4
        with:
          name: xiangshan-user-guide-html
          path: xiangshan-user-guide.html
