name: release

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Release name (tag name)'
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set tag name
        id: vars
        run: echo "TAG_NAME=${{ github.event.inputs.release_name }}" >> $GITHUB_ENV

      - name: Create tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin master
          git checkout master
          git tag $TAG_NAME
          git push origin $TAG_NAME

  trigger-build:
    needs: create-release
    uses: ./.github/workflows/build-pandoc.yml
    secrets: inherit

  publish-release:
    needs: trigger-build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.release_name }}
          name: ${{ github.event.inputs.release_name }}
          files: artifacts/**/*.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
